export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FINISHED = "FETCH_USERS_FINISHED";
export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_FINISHED = "DELETE_USERS_FINISHED";
export const EDIT_USERS = "EDIT_USERS";
export const EDIT_USERS_FINISHED = "EDIT_USERS_FINISHED";
export const ADD_USERS = "ADD_USERS";
export const ADD_USERS_FINISHED = "ADD_USERS_FINISHED"